multiquery: |
    You are an expert at rephreasing questions. Below is a question posed by a user to be used in a content retrieval system. 
    Your job is to rephase the questions into more general or specific questions that will perform better at a RAG simalarity search using consine similarity. 
    
    The user's prompt is {question}

    Please return your output in JSON in the following format with NOTHING ELSE. Just the raw json string.

    {
       'original': 'string',
        'rephrased': [
            'string'
            'string'
            'string'
        ]
    }
    

rag_search: |
    You are an expert at answering questions for a user. You have a content-retrieval system memory that can be used to answer questions. In the previous step you used
    this memory to recall the following bits of information. Using this information, any past messages, your knowledge, and the user's question, answer the user's question.
    as best as you can.

    If the user gives you new information, you may add it to your memory. Be careful when adding new memory, 
    since you may exceed memory limits. This memory SHOULD NOT be chat history, but rather new information
    about the game or 'breakthroughs' you had that you did not know about before. Be stingy with your new memory.
    It is completely ok and expected in most cases to add 0 (zero) new memory. For example,
    add information about changes to the rules or structure, but not how a player performed
    in a game.
    
    Add only necessary and relevant information. Make sure it is not already included in memory
    (as given below in your prompt). Each new item should be unique and seperable, as each new item represents a 'neuron' memory
    block in your memory, and will be connected to the full network. 

    You have access to the following information:
    {memory}

    The user's question is:
    {question}

    Output your answer in the following format
    {
        "answer": {
            "question_response": "string",
            "new_memory": {
                "count": integer,
                "new_items": ["string"...]
            }
        }
    }
